yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug>/', views.group_posts, name='group'),
    path('new/', views.new_post, name='new_post'),
    path('<str:username>/', views.profile, name='profile'),
    path('<str:username>/<int:post_id>/', views.post_view, name='posts'),
    path('<str:username>/<int:post_id>/edit/',
         views.post_edit, name='post_edit'),
]

yatube/users/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup')
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path("admin/", admin.site.urls),
    path("", include("posts.urls")),
]

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField('date published', auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='posts')
    group = models.ForeignKey(Group, on_delete=models.SET_NULL,
                              blank=True, null=True, related_name='posts')

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.text[:15]

    @property
    def pub_date_format(self):
        return self.pub_date.strftime('%d %b %Y')

yatube/posts/forms.py
from django.forms import ModelForm

from .models import Post


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group')

yatube/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

yatube/posts/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from .forms import PostForm
from .models import Group, Post, User


def index(request):
    post_list = Post.objects.all()
    paginator = Paginator(post_list, settings.NUMBER_OF_POSTS_ON_PAGE)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(request, 'misc/index.html', {'page': page, })


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = Post.objects.filter(group=group)
    paginator = Paginator(posts, settings.NUMBER_OF_POSTS_ON_PAGE)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(request, 'posts/group.html', {
        'group': group, 'page': page,
    })


def profile(request, username):
    user = get_object_or_404(User, username=username)
    number_of_posts = Post.objects.filter(author_id=user.id).count()
    paginator = Paginator(user.posts.all(), settings.NUMBER_OF_POSTS_ON_PAGE)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(request, 'misc/profile.html', {
        'number_of_posts': number_of_posts, 'page': page, 'author': user,
    })


def post_view(request, username, post_id):
    user = get_object_or_404(User, username=username)
    number_of_posts = Post.objects.filter(author_id=user.id).count()
    post = get_object_or_404(Post, id=post_id, author_id=user.id)
    return render(request, 'posts/post.html', {
        'number_of_posts': number_of_posts, 'post': post, 'author': user,
    })


@login_required
def new_post(request):
    form = PostForm()
    if request.method == 'GET':
        return render(request, 'posts/new.html', {'form': form, })
    elif request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post: Post = form.save(False)
            post.author = request.user
            post.save()
            return redirect('index')
        return render(request, 'posts/new.html', {'form': form})
    return render(request, 'posts/new.html', {'form': form, })


@login_required
def post_edit(request, username, post_id):
    post = get_object_or_404(Post, pk=post_id, author__username=username)
    if request.user != post.author:
        return redirect('posts', username=username, post_id=post_id)
    form = PostForm(request.POST or None, instance=post)
    if form.is_valid():
        post.save()
        return redirect('posts', username=username, post_id=post_id)
    return render(request, 'posts/new.html', {'form': form, 'post': post})

yatube/users/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('login')
    template_name = "users/signup.html"

yatube/templates/about/author.html
<!-- templates/about/author.html -->
{% extends "misc/base.html" %}
{% block title %}Автор проект - Надежда Гурова{% endblock %}
{% block content %}
  <div class="row">
    <!-- Левый вспомогательный блок -->
    <div class="col-md-3 mb-3 mt-1">
      <div class="card">
        <div class="card-body">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              <div class="h3">
                Автор: Надежда Гурова
              </div>
            </li>
            <li class="list-group-item">
              <div class="h6 text-muted">
                <p>Студентка Яндекс Практикума</p>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <!-- Тело страницы -->
    <div class="col-md-9">
      <div class="card-body">
        <div class="card-text">
          <p>Программирование - наше все!</p>
            <p><a href="https://github.com/Nadezhda-Gurova?tab=projects" target="_blank">Посмотреть другие проекты!</a></p>

            {% load static %}
            <img src="{% static 'cat.jpg' %}" alt="My image" width="700" height="500">
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/about/tech.html
<!-- templates/about/author.html -->
{% extends "misc/base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
  <div class="row">
    <!-- Левый вспомогательный блок -->
    <div class="col-md-3 mb-3 mt-1">
      <div class="card">
        <div class="card-body">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              <div class="h3">
                Автор: Надежда Гурова
              </div>
            </li>
            <li class="list-group-item">
              <div class="h6 text-muted">
                <p>Студентка Яндекс Практикума</p>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <!-- Тело страницы -->
    <div class="col-md-9">
      <div class="card-body">
        <div class="card-text">
          <p>В проекте использованы:</p>
            <ul>
            <li>Python</li>
            <li>Django</li>
            </ul>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/misc/authors_card.html
<div class="card">
    <div class="card-body">
        <div class="h2">
            {{ author.get_full_name }}
        </div>
        <div class="h3 text-muted">
            @{{ author.username }}
        </div>
    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">
            <div class="h6 text-muted">
                Подписчиков: XXX <br>
                Подписан: XXX
            </div>
        </li>
        <li class="list-group-item">
            <div class="h6 text-muted">
                Записей: {{ author.posts.count }}
            </div>
        </li>
    </ul>
</div>

yatube/templates/misc/base.html
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}The Last Social Media You'll Ever Need{% endblock %} | Yatube</title>
    <!-- Загрузка статики -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">
    <script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
  </head>
  <body>
    {% include 'misc/nav.html' %}
    <main>
      <div class="container">
        <h1>{% block header %}The Last Social Media You'll Ever Need{% endblock %}</h1>
        {% block content %}
          <!-- Содержимое страницы -->
        {% endblock content %}
      </div>
    </main>
  {% include 'misc/footer.html' %}
  </body>
</html>

yatube/templates/misc/footer.html
<!-- Шаблон footer.html -->
<footer class="pt-4 my-md-5 pt-md-5 border-top">
  <p class="m-0 text-dark text-center ">
    <a href="{% url 'about:author' %}">Об авторе</a>
    <a href="{% url 'about:tech' %}">Технологии</a>
  </p>
  <p class="m-0 text-dark text-center ">
    Социальная сеть <span style="color:red">Ya</span>tube
  </p>
</footer>

yatube/templates/misc/index.html
{% extends "misc/base.html" %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block header %}Последние обновления на сайте{% endblock %}
{% block content %}

  {% for post in page %}
    <h3>
      Автор: {{ post.author.get_full_name }}, Дата публикации: {{ post.pub_date|date:"d M Y" }}
    </h3>
    <p>{{ post.text|linebreaksbr }}</p>
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}

  {% include "misc/paginator.html" %}
{% endblock %}

yatube/templates/misc/nav.html
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
  <a class="navbar-brand" {% url 'index' %}><span style="color:red">Ya</span>tube</a>
  <nav class="my-2 my-md-0 mr-md-3">
    {% if user.is_authenticated %}
      Пользователь: {{ user.username }}.
        <a class="p-2 text-dark" href="{% url 'new_post' %}">Новая запись</a>
      <a class="p-2 text-dark" href="{% url 'password_change' %}">Изменить пароль</a>
      <a class="p-2 text-dark" href="{% url 'logout' %}">Выйти</a>
    {% else %}
      <a class="p-2 text-dark" href="{% url 'login' %}">Войти</a> |
      <a class="p-2 text-dark" href="{% url 'signup' %}">Регистрация</a>
    {% endif %}
  </nav>
</nav>

yatube/templates/misc/paginator.html
{% if page.has_other_pages %}
  <nav>
    <ul class="pagination">
      {% if page.has_previous %}
        <li class="page-item">
          <a
            class="page-link"
            href="?page={{ page.previous_page_number }}">&laquo; Предыдущая</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link">&laquo; Предыдущая</span>
        </li>
      {% endif %}
      {% for i in page.paginator.page_range %}
        {% if page.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}
              <span class="sr-only">(текущая)</span>
            </span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if page.has_next %}
        <li class="page-item">
          <a
            class="page-link"
            href="?page={{ page.next_page_number }}">Следующая &raquo;</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link">Следующая &raquo;</span>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

yatube/templates/misc/post_card.html
<div class="card mb-3 mt-1 shadow-sm">
    <div class="card-body">
        <p class="card-text">
            <a href="{% url 'profile' username=author.username %}">
                <strong class="d-block text-gray-dark">
                    @{{ author.username }}
                </strong>
            </a>
            {{ post.text }}
        </p>
        <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group ">
                <a class="btn btn-sm text-muted"
                   href="{% url 'posts' username=author.username post_id=post.id %}"
                   role="button">
                    Добавить комментарий
                </a>
                {% if user == post.author %}
                    <a class="btn btn-sm text-muted"
                       href="{% url 'post_edit' username=author.username post_id=post.id %}"
                       role="button">
                        Редактировать
                    </a>
                {% endif %}

            </div>
            <small class="text-muted">{{ post.pub_date|date:"d M Y" }}
                г.</small>
        </div>
    </div>
</div>

yatube/templates/misc/profile.html
{% extends "misc/base.html" %}
{% block content %}
    <main role="main" class="container">
        <div class="row">
            <div class="col-md-3 mb-3 mt-1">
                {% include 'misc/authors_card.html' %}
            </div>
            <div class="col-md-9">
                {% for post in page %}
                    {% include 'misc/post_card.html' %}
                {% endfor %}
                {% include "misc/paginator.html" %}
            </div>
        </div>
    </main>
{% endblock %}

yatube/templates/posts/group.html
{% extends "misc/base.html" %}
{% block title %}Записи сообщества {{ group.title }}{% endblock %}
{% block header %}{{ group.title }}{% endblock %}
{% block content %}

    <p>{{ group.description }}</p>
    {% for post in page %}
    <h3>
        Автор: {{ post.author.get_full_name }}, дата публикации: {{ post.pub_date_format }}
    </h3>
    <p> {{ post.text }}</p>
    {% endfor %}
{% include "misc/paginator.html" %}
{% endblock %}

yatube/templates/posts/new.html
{% extends "misc/base.html" %}
{% block title %}Новая запись{% endblock %}
{% block content %}
    <div class="row justify-content-center">
        <div class="col-md-8 p-5">
            <div class="card">
                {% url 'new_post' as new_post %}
                {% if request.path == new_post %}
                    {% url 'new_post' %}
                    <div class="card-header">Добавить запись</div>
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary"> Добавить</button>
                        </form>
                    </div>
                {% else %}
                    <div class="card-header">Редактировать запись</div>
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary"> Сохранить</button>
                        </form>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

yatube/templates/posts/post.html
{% extends "misc/base.html" %}
{% block content %}
    <main role="main" class="container">
        <div class="row">
            <div class="col-md-3 mb-3 mt-1">
                {% include 'misc/authors_card.html' %}
            </div>
            <div class="col-md-9">
                {% include 'misc/post_card.html' %}
            </div>
        </div>
    </main>
{% endblock %}

yatube/templates/users/signup.html
{% extends "misc/base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  {# загружаем фильтр #}
  {% load user_filters %}

  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
        <div class="card-body">

          {% for error in form.errors %}
            <div class="alert alert-danger" role="alert">
              {{ error }}
            </div>
          {% endfor %}

          <form method="post" action="{% url 'signup' %}">
            {% csrf_token %}
            {% for field in form %}
              <div class="form-group row" aria-required={{ field.field.required }}>
                <label
                  for="{{ field.id_for_label }}"
                  class="col-md-4 col-form-label text-md-right">
                  {{ field.label }}
                  {% if field.field.required %}
                    <span class="required">*</span>
                  {% endif %}
                </label>
                <div class="col-md-6">
                  {# подключаем фильтр и указываем класс #}
                  {{ field|addclass:"form-control" }}
                  {% if field.help_text %}
                    <small
                      id="{{ field.id_for_label }}-help"
                      class="form-text text-muted">
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}
                </div>
              </div>
            {% endfor %}

            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Зарегистрироваться
              </button>
            </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->

{% endblock %}